# Site
url: https://tony9402.github.io
baseurl: /resume
repository: tony9402/resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 김민상
title: <Title>
email: tony9402@naver.com
# email_title: Email (Email title override)
phone:
# phone_title: Phone (Phone title override)
website:
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username:
github_username: tony9402
stackoverflow_username:
dribbble_username:
facebook_username:
flickr_username:
instagram_username:
linkedin_username: tony9402
xing_username:
pinterest_username:
youtube_username:
orcid_username:
googlescholar_username:

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_title: About Me
about_profile_image: images/profile.jpeg
# Directory of profile image (eg. images/profile.jpeg)
about_content: | # this will include new lines to allow paragraphs
  Writing

  <p id="elapsed"></p>

  <script>
    const start = new Date("2024-04-19T00:00:00+09:00");
    const endExclusive = new Date("2027-04-18T00:00:00+09:00");
    const elapsedEl = document.getElementById("elapsed");

    function clamp(n, a, b) { return Math.min(b, Math.max(a, n)); }

    function update() {
      const now = new Date();
      const raw = ((now - start) / (endExclusive - start)) * 100;
      const percent = clamp(raw, 0, 100);

      elapsedEl.textContent = "전문연구요원 복무중 (2024.04.19 - 2027.04.18) (" + percent.toFixed(7) + "%)";
    }
    update();
    setInterval(update, 100);
  </script>

#  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.
#
#  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#    - Lists
#    - Tables
#    - <a href="google.com">Links</a>
#    - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  ###
  ###
  - title: Work Experience
    layout: list
    content:
      - layout: top
        title: ㈜ 와이즈넛
        sub_title: NLP Researcher
        caption: 2024.04 - present
        link: www.wisenut.com
        link_text: 회사 링크
        description: | # this will include new lines to allow paragraphs
          <p style="font-size: 20px; margin-top: 20px;"><strong>Retriever 모델 연구</strong></p>
          - 검색 모델(query to document, document to document) 학습 및 평가 파이프라인 개발
          - In Batch Negative Sampling을 위한 데이터 로더 개발
          - Programming Language
            - Python
          - Containerization
            - <a href="https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html" target="_blank">Docker (NVIDIA Container Toolkit / nvidia-docker)</a>
          - Distributed Training
            - DeepSpeed
            - FSDP
          - NLP / LLM Frameworks & Libraries
            - <a href="https://github.com/huggingface/transformers" target="_blank">transformers</a>
            - <a href="https://github.com/huggingface/sentence-transformers" target="_blank">sentence-transformers</a>
          - Vector Search
            - FAISS

          <p style="font-size: 20px; margin-top: 20px;"><strong>LLM Edge Case 평가 연구</strong></p>
          - 기존 오프라인 평가 결과와 실사용 환경 성능 간 괴리를 발견하고, 이를 검증·보완하기 위한 엣지 케이스 평가셋 개발.
          - Edge Case 평가 모듈 개발

          <p style="font-size: 20px; margin-top: 20px;"><strong>LLM 태스크 특화 모델 연구</strong></p>
          - 기존 성능을 유지한채로 초안 작성 기능을 추가하기 위한 Fine Tuning 연구
          - 학습/평가 데이터 구축을 위한 전처리 알고리즘 개발
          - Containerization
            - <a href="https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html" target="_blank">Docker (NVIDIA Container Toolkit / nvidia-docker)</a>
          - Distributed Training
            - DeepSpeed
            - FSDP
          - NLP/ LLM Frameworks & Libraries
            - <a href="https://github.com/huggingface/transformers" target="_blank">transformers</a>
            - LLama Factory
            - Peft
            - lm-eval-harness
            - vLLM
  ###
  ###
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        # border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: 자동 GPU Cloud에 딥러닝 학습 실험 업로드 모듈 
        link: https://github.com/tony9402/kiml-monitoring
        link_text: 프로젝트 Github 링크
#        additional_links:
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#          - title:  Github page for project (eg. sproogen/modern-resume-theme)
#            icon: fab fa-github
#            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#        quote: >
#          Short overview of the project (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description about the work on/with the project
      - layout: top
        # border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "코딩테스트 대비 문제집 (6.3K Stars)"
        link: https://github.com/tony9402/baekjoon
        link_text: 프로젝트 Github 링크
  ###
  ###
  - title: Open Source Contribution
    layout: list
    content:
      - layout: top
        title: "huggingface/transformers (154K Stars)"
        link: https://github.com/huggingface/transformers
  ###
  ###
  - title: Activity
    layout: list
    content:
      - layout: top
        title: Software Maestro
        sub_title: 11기 (팀명 TrustNet)
        caption: 2020.06 - 2020.12
        link: swmaestro.org
        description: |
          소프트웨어 마에스트로 11기 TrustNet 팀명으로 DeepFake로 조작된 영상을 검출하는 솔루션을 개발하는 프로젝트를 진행하였습니다.

          11기 주요 프로젝트에 포함되었습니다.
          - https://www.swmaestro.org/sw/singl/projectIntc/list.do?menuNo=200013
      - layout: top
        title: Bixby Crew (Samsung Electronics)
      - layout: top
        title: 알고리즘 문제 출제 및 검수
        description: |
          - 약 1200 문제 출제 및 검수
      - layout: top
        title: 알고리즘 멘토링
        description: |
         - 2023 Summer
         - 2023 Winter
         - 2024 Winter
         - 2024 Summer
         - 2025 Summer
      - layout: top
        title: 알고리즘 책 리뷰어 및 검수
        description: |
          - (베타 리뷰) <a href="https://github.com/bjpublic/javarithms" target="_blank">자료구조와 알고리즘을 함께 Java!</a>
          - (검수중) 실전 코딩 테스트 가이드
  ###
  ###
  - title: Education
    layout: list
    content:
      - layout: top
        title: Soongsil University
        sub_title: 석사 - 융합소프트웨어학과
        caption: 2021.09 - 2023.08
        link: sw.ssu.ac.kr
      - layout: top
        title: Soongsil University
        sub_title: 학사 - 컴퓨터학부(복수전공)
        caption: 2018.09 - 2021.08
        link: cse.ssu.ac.kr
      - layout: top
        title: Soongsil University
        sub_title: 학사 - 전자공학전공 (주전공)
        caption: 2017.03 - 2021.08
        link: infocom.ssu.ac.kr

  - title: Publication
    layout: list
    content:
      - layout: top-middle
        title: 특허
      - layout: top
        title: "모션인식을 활용한 자동 수화 번역 제공 시스템 및 그 방법"
        sub_title: 특허 - 출원 (2020.12)
      - layout: top-middle
        title: 국내 논문
      - layout: top
        title: "가이던스 기반 이중 에이전트 프레임워크를 통한 실시간 검색 성능 향상"
        sub_title: "김민상, 박찬솔, 최승호, 박시현, 김봉수, HCLT 2025"
        link: https://sites.google.com/view/hclt-2025
        link_text: 학회 홈페이지
      - layout: top
        title: "지속학습을 위한 하드 네거티브 샘플링 기반 검색 모델 향상 기법"
        sub_title: "김민상, 최승호, 박시현, 박찬솔, 왕준호, 김지윤, 김봉수, HCLT 2024"
        link: https://sites.google.com/view/hclt2024
        link_text: 학회 홈페이지
      - layout: top
        title: "향상된 특징 추출 기반의 극한 다중 레이블 특허 분류 기법"
        sub_title: "김민상, 학위논문"
        link: https://www.dbpia.co.kr/journal/detail?nodeId=T16784793
        link_text: 논문 링크
      - layout: top-middle
        title: 해외 논문
      - layout: top
        title: "HanjaBridge: Resolving Semantic Ambiguity in Korean LLMs via Hanja-Augmented Pre-Training"
        sub_title: "Seungho Choi*, Sihyun Park*, Minsang Kim*, Chansol Park*, Bongsu Kim*, AAAI 2026"
        link: https://aaai.org/conference/aaai/aaai-26/main-technical-track
        link_text: 학회 링크 (논문 공개 전)
      - layout: top
        title: "Robust DeepFake Detection Method based on Ensemble of ViT and CNN"
        sub_title: "Hyunsoo Ha, Minsang Kim, Songhun Han, Sangjun Lee, SAC 2023 Poster"
        link: https://dl.acm.org/doi/10.1145/3555776.3577769
        link_text: 논문 링크

  - title: Award and Honors
    layout: list
    content:
      - layout: top-middle
        title: 장학금
      - layout: top
        title: 2020-1학기 숭실대학교 IT미래인재장학금 선발
        sub_title: 2019.12
        link: https://sw.ssu.ac.kr/bbs/board.php?bo_table=notice&wr_id=1047
        link_text: 선발 발표
      - layout: top
        title: 2019-2학기 숭실대학교 IT미래인재장학금 선발
        sub_title: 2019.06
        link: https://sw.ssu.ac.kr/bbs/board.php?bo_table=notice&wr_id=954
        link_text: 선발 발표
#      - layout: top
#        title: 2023 전국 대학생 프로그래밍 대회 (UCPC) 예선 17위, 본선 30위
#        sub_title: 2023.07
#        link: 
#      - layout: top
#        title: 2022 전국 대학생 프로그래밍 대회 (UCPC) 예선 41위, 본선 45위
#        sub_title: 2022.07
#        link:
#        - "https://www.acmicpc.net/contest/spotboard/827"
#        - "https://www.acmicpc.net/contest/spotboard/828"
      - layout: top-middle
        title: 수상
      - layout: top
        title: ACM-ICPC Daejeon Regional 35th place
        sub_title: 2021.11
      - layout: top
        title: ACM-ICPC 교내 예선 2위
        sub_title: 2021.10
      - layout: top
        title: 청년창업아이디어 경진대회 특별상
        sub_title: 2020.12
      - layout: top
        title: 숭실대학교 IT 대학 알고리즘 대회 3위
        sub_title: 2020.11
      - layout: top
        title: 숭실대학교 캡스톤 경진대회 은상
        sub_title: 2020.10
      - layout: top
        title: 브랜디 코드네임B 입상
        sub_title: 2020.10
      - layout: top
        title: Bixby Capsule Challenge (시즌 2) 동상
        sub_title: 2019.12
      - layout: top
        title: ACM-ICPC Daejeon Regional 16th place
        sub_title: 2019.11
      - layout: top
        title: ACM-ICPC 교내 예선 2위
        sub_title: 2019.10
      - layout: top
        title: 숭실대학교 IT대학 소프트웨어 공모전 동상
        sub_title: 2019.09
      - layout: top
        title: 숭실대학교 캡스톤 경진대회 장려상
        sub_title: 2019.09
#      - layout: top
#        title: 2019 전국 대학생 프로그래밍 대회 (UCPC) 예선 46위
#        sub_title: 2019.07
      - layout: top
        title: Bixby Capsule Challenge (시즌 1) 7위
        sub_title: 2019.07
      - layout: top
        title: 숭실대학교 교내 알고리즘 대회 SCON 4위
        sub_title: 2019.05
      - layout: top
        title: 숭실대학교 교내 알고리즘 대회 Spring Contest 7위
        sub_title: 2019.04
      - layout: top
        title: SoC Robot War (SoC 태권로봇) 3위
        sub_title: 2018.08
      - layout: top
        title: 숭실대학교 캡스톤 경진대회 우수상
        sub_title: 2017.09

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
